/**
 * Colors dùng chung cho toàn app
 */
export const colors = {
  primary: 'rgb(20, 53, 195)',
  secondary: 'skyblue',
  text: 'black',
  secondaryText: 'rgb(67, 70, 87)',
  tertiaryText: 'rgb(130, 134, 158)',
  placeholderText: '#82869E',
  disabledText: '',
  link: '',
  cursor: 'rgb(20, 53, 195)',
  selection: '',
  border: '#ebedf0',
  divider: '#ebedf0',
  notification: '#da4343',
  error: '#da4343',
  warning: '',
  info: '',
  success: '',
  background: '#f2f2f6',
  surface: '#ffffff',
  whitesmoke: '#f5f5f5',
  darkgray: '#a9a9a9',
  gainsboro: '#dcdcdc',
  dimgray: '#696969',
  backdrop: 'rgba(0,0,0,0.5)',
  placeholderImage: '#f6f6f6',
  disabledInputBackground: '#f8f8fc',
  light: '#ffffff',
  messageBackground: 'rgba(0,0,0,0.75)',
  searchBackground: '#f6f6f6',
  star: 'orange',
};
